### ISSUE TITLE
Ionic SyntaxError: Unexpected character in node_aes_gcm.node

### ISSUE THREAD

**Issue by Huiting-Yeong** [xorbit/node-aes-gcm#6]
I am making my application using `Ionic 2.0.0-beta.4` and trying to using node-aes-gcm for encryption.
I have installed it and ran `node-gyp rebuild` to get the build file and `node_aes_gcm.node`.

However when I build it on Ionic, it gives me a syntax error:

> SyntaxError: Unexpected character 'SyntaxError: Unexpected character '�' (2:2) while parsing C:\Users\JK\Desktop\MyIonic2Project\MyIonic2ProjectTest\node_modules\node-aes-gcm\build\Release\node_aes_gcm.node while parsing file: C:\Users\JK\Desktop\MyIonic2Project\MyIonic2ProjectTest\node_modules\node-aes-gcm\build\Release\node_aes_gcm.node

Any suggestions to make it run on Ionic?

**Comment by xorbit** [comment]
I do not, I'm sorry.  I've only used this with node.js.
Does Ionic support native / compiled packages?  That's what this project is (it links to OpenSSL).  The error message looks like the problem occurs when loading the compiled .node file.

**Comment by xorbit** [comment]
Since I didn't get any response to this issue, don't use Ionic and don't know if it's supposed to support compiled native modules which depend on V8, I'm closing this issue.
